[package]
name = "tokio-fluent"
version = "0.2.1"
authors = ["johnmanjiro13"]
edition = "2021"
description = "A fluentd client using tokio"
license = "MIT"
repository = "https://github.com/johnmanjiro13/tokio-fluent"
keywords = ["fluentd", "tokio"]
readme = "README.md"
include = [
  "**/*.rs",
  "Cargo.toml",
  "README.md"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.61"
crossbeam = "0.8.2"
log = "0.4.17"
rmp-serde = "1.1.1"
serde = {version = "1.0.152", features = ["derive"]}
tokio = {version = "1.23.0", features = ["full"]}
