name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      fluentd:
        image: fluent/fluentd
        ports:
          - 24224:24224
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run clippy
        run: cargo clippy
      - name: Run cargo fmt
        run: cargo fmt --check
      - name: Run test
        run: cargo test
